const _products = [
    {
        id: 1,
        name:"Ore Sweater",
        size: 'M, XL, XXL',
        color: 'Custom made to what you want',
        price: '15000',
        public_id:"store/store4_rlkr3u",
        quantityInStock: 20,
    },
    {
        id: 2,
        name: 'McPherson T-shirt',
        size: 'S, M, L',
        color: 'White',
        price: '4000',
        public_id:"store/store2_iuj9gd",
        quantityInStock: 13,
    },
    {
        id: 3,
        name: 'McPherson Summer T-shirt',
        size: 'S, M, L',
        color: 'Green',
        price: '3500',
        public_id:"store/store3_ph4qw4",
        quantityInStock: 50,
    },
    {
        id: 4,
        name: 'Karpos Shoes',
        size: '39 - 43',
        color: 'Brown, Black',
        price: '19500',
        public_id: "store/store7_rkjrdo",
        quantityInStock: 43,
    },
    {
        id: 5,
        name: 'Rainbow T-shirt',
        size: 'S, M, L',
        color: 'As seen in the picture',
        price: '5000',
        public_id:"store/store11_td1at8",
        quantityInStock: 20,
    },
    {
        id: 6,
        name: 'Gregory Shoes',
        size: '37 - 40',
        color: 'Yellow, Black',
        price: '10500',
        public_id: "store/store5_sht2jx",
        quantityInStock: 10,
    },
    {
        id: 20,
        name: 'RTote bag',
        size: '',
        color: 'As seen in the picture',
        price: '6000',
        public_id:"store/store22_cww7ir",
        quantityInStock: 80,
    },
    {
        id: 8,
        name: 'Gregory Shoes',
        size: '37 - 40',
        color: 'Yellow, Black',
        price: '9000',
        public_id: 'store/store9_zfk83z',
        quantityInStock: 32,
    },
    {
        id: 10,
        name: 'Dina Sneakers',
        size: '10 - 12 UK',
        color: 'White',
        price: '15000',
        public_id: "store/store8_zzqcom",
        quantityInStock: 30,
    },
    {
        id: 16,
        name: 'Lisa leather bag',
        size: '',
        color: 'Brown',
        price: '9500',
        public_id: "store/store20_ui9b7a",
        quantityInStock: 15,
    },
    {
        id: 11,
        name: 'Colorful sneakers',
        price: '11000',
        size: '36 - 42',
        color: 'As seen in the picture',
        public_id:"store/store10_iyovip",
        quantityInStock: 22,
    },
    {
        id: 12,
        name: 'Women underwear',
        size: 'S, M, L',
        color: 'Black, White, Red, Blue',
        price: '2000',
        public_id:"store/store14_rrxsc6",
        quantityInStock: 43,
    },
    {
        id: 13,
        name: 'Men full sleeve shirt',
        size: 'S, M, L',
        color: 'As seen in the picture',
        price: '6500',
        public_id: "store/store12_xle1ms",
        quantityInStock: 21,
    },
    {
        id: 14,
        name: 'Beach shirt',
        size: 'S, M, L',
        color: 'As seen in the picture',
        price: '8000',
        public_id:"store/store13_spy0sm",
        quantityInStock: 44,
    },
    {
        id: 15,
        name: 'Mira Crop top',
        size: 'S, M',
        color: 'Gold, Black',
        price: '6500',
        public_id: "store/store16_l6imqy",
        quantityInStock: 65,
    },
    {
        id: 18,
        name: 'Anna chic clutch',
        size: '',
        color: 'Green, Brown, Black, White, Lavendar',
        price: '3000',
        public_id:"store/store21_nz4gfa",
        quantityInStock: 102,
    },
    {
        id: 19,
        name: 'Women 2021 fashion bag',
        size: '',
        color: 'Orange',
        price: '5300',
        public_id: "store/store19_rezbmn",
        quantityInStock: 21,
    },
    
    {
        id: 7,
        name: 'Concordia loafers',
        size: '41 - 44',
        color: 'Brown',
        price: '12000',
        public_id: "store/store6_rt2ywb",
        quantityInStock: 42,

    },
   
]

export default {
    getProducts(cb) {
      setTimeout(() => cb(_products), 500)
    }
}
  